###
# @name Embedding - Test embedding response
POST {{galyarder-route-address}}/v1/embeddings
Authorization: Bearer {{GALYARDER_ROUTE_API_KEY}}
Content-Type: application/json

{
  "model": "pinecone/llama-text-embed-v2",
  "input": "The food was delicious and the waiter was very attentive."
}

